/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelDominio.Bebida;
import modelDominio.Prato;
import modelDominio.Produto;
import view.util.Imagem;

/**
 *
 * @author aluno
 */
public class TelaEditarProduto extends javax.swing.JFrame {

    private Imagem imagem = null;
    private Produto eProduto;
    

    /**
     * Creates new form TelaEditarProduto
     */
    public TelaEditarProduto(Produto produto) {
        initComponents();
        eProduto = produto;
         preencherCampos();  

    }

    public void preencherCampos() {
    if (eProduto != null) {
        jTFEditarNome.setText(eProduto.getNomeProduto());
        jTxtEditarDescricao.setText(eProduto.getDescricao());
        jFTEditarValor.setValue(eProduto.getValor());
        jTFEditarTempo.setText(eProduto.getTempo());
        jFTEditarData.setValue(eProduto.getData());

        if (eProduto instanceof Prato) {
            JCBEditarCombo.setSelectedItem("Prato");
        } else if (eProduto instanceof Bebida) {
            JCBEditarCombo.setSelectedItem("Bebida");
        }

    }
}
    /**
     * Creates new form TelaEditarProduto
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBVoltar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFEditarNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtEditarDescricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jFTEditarValor = new javax.swing.JFormattedTextField();
        jTFEditarTempo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFTEditarData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JCBEditarCombo = new javax.swing.JComboBox<>();
        jblImagem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(741, 686));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 58, 58));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));

        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/left-arrow.png"))); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/logo certa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel9)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 150));

        jPanel2.setBackground(new java.awt.Color(241, 237, 237));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 753, 152, 65));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/elipse 1 login.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 329, -1, -1));
        jPanel2.add(jTFEditarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 348, 234, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 351, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descrição:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 388, -1, -1));

        jTxtEditarDescricao.setColumns(20);
        jTxtEditarDescricao.setRows(5);
        jScrollPane1.setViewportView(jTxtEditarDescricao);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 388, 240, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Valor");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 500, -1, -1));

        jFTEditarValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jPanel2.add(jFTEditarValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 497, 234, -1));
        jPanel2.add(jTFEditarTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 537, 234, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tempo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 540, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 580, -1, -1));

        jFTEditarData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel2.add(jFTEditarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 577, 234, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tipo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 623, -1, -1));

        JCBEditarCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecionar>>", "Prato", "Bebida" }));
        jPanel2.add(JCBEditarCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 617, 234, -1));

        jblImagem.setText("Carregar Imagem");
        jblImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblImagemActionPerformed(evt);
            }
        });
        jPanel2.add(jblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 691, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/elipse 2 login.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 519, -1, -1));
        jPanel2.add(jtxtImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 669, 116, 126));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 760, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
           float valor;
    Date data;
    try {
        valor = ((Number) jFTEditarValor.getValue()).floatValue();
    } catch (Exception e) {
        valor = 0;
    }
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        data = sdf.parse(jFTEditarData.getText());
    } catch (Exception e) {
        data = null;
        e.printStackTrace();
    }

    if (jTFEditarNome.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Preencha o campo Nome.",
                this.getTitle(), JOptionPane.ERROR_MESSAGE);
        jTFEditarNome.requestFocus();
    } else if (jTxtEditarDescricao.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Preencha o campo Descrição.",
                this.getTitle(), JOptionPane.ERROR_MESSAGE);
        jTxtEditarDescricao.requestFocus();
    } else if (valor <= 0) {
        JOptionPane.showMessageDialog(this, "Preencha o campo Valor.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        jFTEditarValor.requestFocus();
    } else if (jTFEditarTempo.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Preencha o campo Tempo.",
                this.getTitle(), JOptionPane.ERROR_MESSAGE);
        jTFEditarTempo.requestFocus();
    } else if (data == null) {
        JOptionPane.showMessageDialog(this, "Preencha o campo Data",
                this.getTitle(), JOptionPane.ERROR_MESSAGE);
        jFTEditarData.requestFocus();
    } else {
        String nomeProduto = jTFEditarNome.getText();
        String descricao = jTxtEditarDescricao.getText();
        String tempo = jTFEditarTempo.getText();
        int tipo = JCBEditarCombo.getSelectedIndex();

        Produto produto;
        if (tipo == 1) {
            produto = new Prato(nomeProduto, descricao, valor, tempo, data, imagem.getImagem(), tipo);
        } else if (tipo == 2) {
            produto = new Bebida(nomeProduto, descricao, valor, tempo, data, imagem.getImagem(), tipo);
        } else {
            return;
        }

        produto.setCodProduto(eProduto.getCodProduto());
        Boolean ok = SakeBonsaiCliente.ccont.editarProduto(produto);

        if (!ok) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreu um erro",
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Produto editado com sucesso!",
                    this.getTitle(),
                    JOptionPane.INFORMATION_MESSAGE);
            TelaProduto telaProduto = new TelaProduto();
            telaProduto.setVisible(true);
            dispose();
        }
    }

        
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jblImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblImagemActionPerformed
        // TODO add your handling code here:
                JFileChooser jFileChooser1 = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            imagem = new Imagem(jFileChooser1.getSelectedFile());
            jtxtImagem.setIcon(imagem.getImageIcon());
        }
    }//GEN-LAST:event_jblImagemActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCBEditarCombo;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JFormattedTextField jFTEditarData;
    private javax.swing.JFormattedTextField jFTEditarValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFEditarNome;
    private javax.swing.JTextField jTFEditarTempo;
    private javax.swing.JTextArea jTxtEditarDescricao;
    private javax.swing.JButton jblImagem;
    private javax.swing.JLabel jtxtImagem;
    // End of variables declaration//GEN-END:variables
}
